version: '3.7'

services:
  app_v2:
    build:
      dockerfile: Dockerfile.v2.alpine
      context: .
    volumes:
      - /app/node_modules/
      - ./:/app/
    security_opt:
      - seccomp=chrome.json
